name: Post daily tweet
on:
  schedule:
    - cron:  '0 13 * * *'

jobs:
  make daily post:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tweepy
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run python script for post
        run: python FeriasUFPA.py
        env:
          CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
          CONSUMER_SECRET_KEY: ${{ secrets.CONSUMER_SECRET_KEY }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_SECRET_TOKEN: ${{ secrets.ACCESS_SECRET_TOKEN }}
